spring:
  application:
   # name of the application
    name: spring-config-server
   # available profiles of the application 
  profiles:
    active: local,development,production
  cloud:
    config:
      server:
        git:
          # git url where the configurations are stored
          uri: https://github.com/prtk45/cloud-config-server
          # if configurations are in sub folders search the subfolder by below name
          search-paths: server-config/
server:
  # config server port
  port: 9001
  
management:
  security:
  # disable security of the config server
   enabled: false